version: '3.7'

services:
#  db_powerbi:
#    image: mcr.microsoft.com/mssql/server:2019-latest
#    restart: on-failure
#    container_name: db_powerbi
#    environment:
#      ACCEPT_EULA: Y
#      SA_PASSWORD: ${DB_POWERBI_FLYWAY_PASSWORD}
#    healthcheck:
#      test: ["CMD-SHELL", "sqlcmd -S ${DB_POWERBI_HOSTNAME} -U ${DB_POWERBI_FLYWAY_USERNAME} -P ${DB_POWERBI_FLYWAY_PASSWORD} -Q 'SELECT 1' || exit 1"]
#      interval: 10s
#      timeout: 3s
#      retries: 10
#      start_period: 10s
#    ports:
#      - 1433:1433

  flyway_powerbi:
    image: quay.io/ukhomeofficedigital/docker-flyway:2e37d154f7a6b74f0064a53ce640e449e082d3ca
    container_name: flyway_powerbi
    command: >
      sh -c "/mnt/docker/run.sh"
    working_dir: /mnt/
    environment:
      DB_POWERBI_DATABRICKS_PASSWORD: ${DB_POWERBI_DATABRICKS_PASSWORD}
      DB_POWERBI_DATABRICKS_USERNAME: ${DB_POWERBI_DATABRICKS_USERNAME}
      DB_POWERBI_DBNAME: ${DB_POWERBI_DBNAME}
      DB_POWERBI_FLYWAY_PASSWORD: ${DB_POWERBI_FLYWAY_PASSWORD}
      DB_POWERBI_FLYWAY_USERNAME: ${DB_POWERBI_FLYWAY_USERNAME}
      DB_POWERBI_HOSTNAME: ${DB_POWERBI_HOSTNAME}
      DB_POWERBI_PORT: ${DB_POWERBI_PORT}
      DB_POWERBI_POWERBI_PASSWORD: ${DB_POWERBI_POWERBI_PASSWORD}
      DB_POWERBI_POWERBI_USERNAME: ${DB_POWERBI_POWERBI_USERNAME}
    volumes:
      - .:/mnt
#    depends_on:
#      - db_powerbi
