CREATE TABLE [dbo].[OAR](
	[Business Key] [nvarchar](250) NOT NULL,
	[Capture Date] [datetime2](7) NULL,
	[Shift Date Time] [datetime2](7) NULL,
	[Total Hours Display] [nvarchar](250) NULL,
	[Total Number of Staff] [int] NULL,
	[Total Minutes Worked] [int] NULL,
	[Total Hours Worked] [int] NULL,
	[Staff Grade] [nvarchar](250) NULL,
	[Customs Activity Undertaken] [int] NULL,
	[Customs Minutes Taken] [int] NULL,
	[Customs Hours Taken] [int] NULL,
	[Staff Activity] [nvarchar](250) NULL,
	[Cyclamen Minutes Taken] [int] NULL,
	[Cyclamen Hours Taken] [int] NULL,
	[Cyclamen Activity] [nvarchar](250) NULL,
	[Detection Minutes Taken] [int] NULL,
	[Detection Hours Taken] [int] NULL,
	[Detection Positive Count] [int] NULL,
	[Detection Negative Count] [int] NULL,
	[Detection Search Activity] [nvarchar](250) NULL,
	[Target Category] [nvarchar](250) NULL,
	[Other Activity Minutes Taken] [int] NULL,
	[Other Activity Hours Taken] [nvarchar](250) NULL,
	[Other Activity] [nvarchar](250) NULL,
	[PCP Minutes taken] [nvarchar](250) NULL,
	[PCP Hours Taken] [int] NULL,
	[PCP Activity] [nvarchar](250) NULL,
	[Location Name] [nvarchar](250) NULL,
	[teamname] [nvarchar](250) NULL,
	[teamcode] [nvarchar](250) NULL,
	[Command ID] [int] NULL,
	[Command Name] [nvarchar](250) NULL,
	[Command Code] [nvarchar](250) NULL,
	[Division ID] [int] NULL,
	[Division Code] [nvarchar](250) NULL,
	[Division Name] [nvarchar](250) NULL,
	[Branch ID] [int] NULL,
	[Branch Code] [nvarchar](250) NULL,
	[Branch Name] [nvarchar](250) NULL,
	[Directorate ID] [int] NULL,
	[Directorate Code] [nvarchar](250) NULL,
	[Directorate Name] [nvarchar](250) NULL,
	[Department ID] [int] NULL,
	[Department Code] [nvarchar](250) NULL,
	[Department Name] [nvarchar](250) NULL,
	[Ministry ID] [int] NULL,
	[Ministry Code] [nvarchar](250) NULL,
	[Ministry Name] [nvarchar](250) NULL
);

